### PR TITLE
Add basic Cucumber features

### LINKED ISSUE #13: Add Cucumber tests!

### PR DESCRIPTION
**Pull request by bsideup**
Closes #13

### CODE REVIEW

**Review by slinkydeveloper — APPROVED** [review]
LGTM

**Comment by bsideup** [comment]
Hey @n3wscott,

WDYT about this one? :)

**Comment by n3wscott** [comment]
LGTM!!

we will have to make a whole bunch of these. 

Can you also add the interface that an sdk has to implement or add that implementation here?

**Comment by bsideup** [comment]
@n3wscott thanks for merging! Time to update sdk-java & sdk-go PRs 🎉 

> Can you also add the interface that an sdk has to implement or add that implementation here?

There is no interface to implement, but the steps (via the framework)

See https://github.com/cloudevents/sdk-go/pull/474 for an example of such

**Comment by n3wscott** [comment]
I mean the contract that cucumber expects to add  these tests to an sdk

**Pull request merged**
